apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: series-stram-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: series-stream
    spec:
      containers:
      - image: lavrinec/series-stream:0.01
        name: series-stream
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: minikube
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
        ports:
        - containerPort: 8080
          name: server
          protocol: TCP