{
  "kind": "Deployment",
  "apiVersion": "extensions/v1beta1",
  "metadata": {
    "name": "series-stram-deployment",
    "namespace": "kube-public",
    "selfLink": "/apis/extensions/v1beta1/namespaces/kube-public/deployments/series-stram-deployment",
    "uid": "4bc983d3-d9c2-11e7-ba94-72c6b65a4c2a",
    "resourceVersion": "240496",
    "generation": 13,
    "creationTimestamp": "2017-12-05T13:43:37Z",
    "labels": {
      "app": "series-stream"
    },
    "annotations": {
      "deployment.kubernetes.io/revision": "6"
    }
  },
  "spec": {
    "replicas": 3,
    "selector": {
      "matchLabels": {
        "app": "series-stream"
      }
    },
    "template": {
      "metadata": {
        "creationTimestamp": null,
        "labels": {
          "app": "series-stream"
        }
      },
      "spec": {
        "containers": [
          {
            "name": "series-stream",
            "image": "lavrinec/series-stream:0.02",
            "ports": [
              {
                "name": "server",
                "containerPort": 8080,
                "protocol": "TCP"
              }
            ],
            "env": [
              {
                "name": "KUMULUZEE_DISCOVERY_CLUSTER",
                "value": "minikube"
              },
              {
                "name": "KUMULUZEE_DISCOVERY_ETCD_HOSTS",
                "value": "http://etcd:2379"
              }
            ],
            "resources": {
              "limits": {
                "cpu": "500m"
              },
              "requests": {
                "cpu": "250m"
              }
            },
            "terminationMessagePath": "/dev/termination-log",
            "terminationMessagePolicy": "File",
            "imagePullPolicy": "IfNotPresent"
          }
        ],
        "restartPolicy": "Always",
        "terminationGracePeriodSeconds": 30,
        "dnsPolicy": "ClusterFirst",
        "securityContext": {},
        "schedulerName": "default-scheduler"
      }
    },
    "strategy": {
      "type": "RollingUpdate",
      "rollingUpdate": {
        "maxUnavailable": "25%",
        "maxSurge": "25%"
      }
    },
    "revisionHistoryLimit": 2,
    "progressDeadlineSeconds": 600
  },
  "status": {
    "observedGeneration": 13,
    "replicas": 3,
    "updatedReplicas": 3,
    "readyReplicas": 3,
    "availableReplicas": 3,
    "conditions": [
      {
        "type": "Progressing",
        "status": "True",
        "lastUpdateTime": "2017-12-08T21:45:29Z",
        "lastTransitionTime": "2017-12-05T13:43:37Z",
        "reason": "NewReplicaSetAvailable",
        "message": "ReplicaSet \"series-stram-deployment-3318244058\" has successfully progressed."
      },
      {
        "type": "Available",
        "status": "True",
        "lastUpdateTime": "2017-12-08T22:21:16Z",
        "lastTransitionTime": "2017-12-08T22:21:16Z",
        "reason": "MinimumReplicasAvailable",
        "message": "Deployment has minimum availability."
      }
    ]
  }
}